language: cpp

os:
 - linux
 - osx

compiler:
  - gcc
  - clang
  
addons:
  apt:
    packages:
    - cmake
    - libasound2-dev
    - libflac++-dev
    - libjack-dev
    - libmpg123-dev
    - libpulse-dev

before_script:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install flac jack mpg123 pulseaudio; fi
  - mkdir build && cd build
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then cmake -DENABLE_FLAC=no ..; else cmake ..; fi

script: make
