language: cpp

compiler:
  - gcc
  - clang
  
addons:
  apt:
    packages:
    - cmake
    - libasound2-dev
    - libflac++-dev
    - libjack-dev
    - libmpg123-dev

before_script:
  - mkdir build
  - cd build
  - cmake ..

script: make
