# See http://www.appveyor.com/docs/appveyor-yml
version: '{build}'

environment:
  matrix:
    - COMPILER: mingw
      GENERATOR: MinGW Makefiles
      PLATFORM: Win32
      BUILD_TYPE: Debug

    - COMPILER: mingw
      GENERATOR: MinGW Makefiles
      PLATFORM: Win32
      BUILD_TYPE: Release

    - COMPILER: mingw-w64
      GENERATOR: MinGW Makefiles
      PLATFORM: x64
      BUILD_TYPE: Debug

    - COMPILER: mingw-w64
      GENERATOR: MinGW Makefiles
      PLATFORM: x64
      BUILD_TYPE: Release

install:
  - if "%COMPILER%"=="mingw" set PATH=C:\MinGW\bin;%PATH%
  - if "%COMPILER%"=="mingw-w64" set PATH=C:\MinGW\bin;%PATH%

before_build:
  - cmake . -Bbuild -G "%GENERATOR%" -DCMAKE_BUILD_TYPE=%BUILD_TYPE% -DENABLE_ALSA=no -DENABLE_FLAC=no -DENABLE_MP3=no -DENABLE_JACK=no -DENABLE_PULSE=no -DENABLE_OSS=n

build_script:
  - cmake --build build --use-stderr --target all --