# See http://www.appveyor.com/docs/appveyor-yml
version: '{build}'

# https://www.appveyor.com/docs/build-environment/#build-worker-images
image: Visual Studio 2017

before_build:
- set Path=C:\mingw-w64\x86_64-7.2.0-posix-seh-rt_v5-rev1\bin;%Path%
- dir C:\mingw-w64\x86_64-7.2.0-posix-seh-rt_v5-rev1\bin\
- g++ --version
- mingw32-make --version
- cmake --version
- echo NUMBER_OF_PROCESSORS=%NUMBER_OF_PROCESSORS%
- if "%APPVEYOR_REPO_TAG%"=="true" (set CMAKE_BUILD_TYPE=Release) else (set CMAKE_BUILD_TYPE=Debug)
- cmake -H. -Bbuild -G "MinGW Makefiles" -DCMAKE_BUILD_TYPE=%CMAKE_BUILD_TYPE% -DENABLE_ALSA=no -DENABLE_FLAC=no -DENABLE_MP3=no -DENABLE_JACK=no -DENABLE_PULSE=no -DENABLE_OSS=n

build_script:
- cmake --build build --use-stderr --target all -- -j%NUMBER_OF_PROCESSORS%